export {default as Blog } from './blog/Blog'
export {default as Features } from './features/Features'
export {default as Footer } from './footer/Footer'
// export {default as Header } from './header1/Header1'
export {default as Possibility } from './possibility/Possibility'
export {default as Kcodeapplied} from './knowCodeapplied/Kcodeapplied'
